version: "3.7"
services:

  kms:
    container_name: kurento-ms
    image: kurento/kurento-media-server
    stdin_open: true
    environment:
      KMS_STUN_IP: 209.85.232.127
      KMS_STUN_PORT: 19302
    ports:
      - 8888:8888